name: startgym
description: Tornando sua vida mais saúdavel.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  font_awesome_flutter: "^8.2.0"
  cloud_firestore: "^0.8.2+3"
  firebase_analytics: "^1.0.6"
  carousel_slider: "^1.0.1"
  scoped_model: "^0.3.0"
  path_provider: "^0.4.1"
  firebase_auth: "^0.7.0"
  url_launcher: "^4.0.1"
  valida_cpf: "^0.0.1"
  http: "^0.12.0"
  google_sign_in: "^3.2.2"
  flutter_map: "^0.3.0"
  location: "^1.4.1"
  image_picker: "^0.4.12"
  firebase_storage: "^1.0.4"
  connectivity: "^0.4.2"
  mailer2: "^1.2.4"
  splashscreen: "^1.2.0"
  qr_flutter: "^2.0.0+51"
  dio: "2.0.23"
  random_string: "0.0.2"
  firebase_database: "^1.0.5"
  flutter_cielo: "1.0.7"
  flutter_masked_text: "0.8.0"
  barcode_scan: "^0.0.8"
  flutter_launcher_icons: "0.7.2"
  google_maps_flutter: "0.5.17"
  fl_chart: "^0.0.8"
  mercado_pago: "^0.1.3"
  onesignal_flutter: "2.0.1"
  cloud_functions: "0.0.5"
  flutter_facebook_login: '^1.1.0'
  crypto: 2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/logo.png
   - images/icon.png
   - images/empty-photo.jpg
   - images/logo-splash.png
   - images/front-card.png
   - images/back-card.png
   - images/master.png
   - images/boleto.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
